backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Logo, name: logo, widget: image}
          - {label: "Mission Statement", name: missionStatement, widget: object, fields: [
              {label: Heading, name: heading, widget: string},
              {label: Statement, name: content, widget: string}
            ]}
          - {label: "Background Image", name: backgroundImage, widget: image}
          - {label: "Social Media", name: socialMedia, widget: List, fields: [
              {label: Icon, name: icon, widget: image},
              {label: Link, name: link, widget: string}
            ]}
          - {label: Heading, name: homePageHeading, widget: object, fields: [
              {label: "Top Text", name: topText, widget: string},
              {label: "Bottom Text", name: bottomText, widget: text}
            ]}
          - {label: Ensembles, name: ensembles, fields: [
              {label: Image, name: image, widget: image},
              {label: Heading, name: heading, widget: string},
              {label: "Small Description", name: description, widget: string},
              {label: Button, name: button, widget: object, fields: [
                {label: "Button Label", name: label, widget: string},
                {label: "Button Link", name: link, widget: string}
              ]}
            ]}
      - file: "src/pages/cu-singers/index.md"
        label: "CU Singers"
        name: "cu-singers"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "cu-singers-page"}
          - {label: Header, name: header, widget: object, fields: [
              {label: "Top Text", name: topText, widget: string},
              {label: "Bottom Text", name: bottomText, widget: text}
            ]}
          - {label: Image, name: image, widget: image}
          - {label: Subheading, name: subheading, widget: string}
          - {label: About, name: about, widget: string}
          - {label: Button, name: button, widget: object, fields: [
              {label: "Button Label", name: buttonText, widget: string},
              {label: "Button Link", name: buttonLink, widget: string}
            ]}
          - {label: "Button Label", name: buttonText, widget: string}
          - {label: "Button Link", name: buttonLink, widget: string}
          - {label: "Second Subheading", name: subheadingTwo, widget: string}
          - {label: "Audition Information", name: auditionInformation, widget: list, fields: [
              {label: Image, name: image, widget: image},
              {label: Heading, name: heading, widget: text},
              {label: Text, name: text, widget: text}
            ]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [
              {label: Heading, name: heading, widget: string},
              {label: Description, name: description, widget: text},
              {label: Blurbs, name: blurbs, widget: list, fields: [
                {label: Image, name: image, widget: image},
                {label: Text, name: text, widget: text}
              ]}
            ]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
