backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "ensembles"
    label: "Ensembles"
    folder: "src/pages/ensembles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "ensembles"}
      - {label: Header, name: header, widget: object, fields: [
          {label: "Top Text", name: topText, widget: string, default: 'Top text'},
          {label: "Bottom Text", name: bottomText, widget: text, , default: 'Bottom Text'}
        ]}
      - {label: Image, name: image, widget: image}
      - {label: Subheading, name: subheading, widget: string}
      - {label: About, name: about, widget: string}
      - {label: Button, name: button, widget: object, fields: [
          {label: "Button Label", name: buttonText, widget: string},
          {label: "Button Link", name: buttonLink, widget: string}
        ]}
      - {label: "Second Subheading", name: subheadingTwo, widget: string}
      - {label: "Audition Information", name: auditionInformation, widget: list, fields: [
          {label: Image, name: image, widget: image},
          {label: Heading, name: heading, widget: text},
          {label: Text, name: text, widget: text}
        ]}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Logo, name: logo, widget: image, required: false}
          - label: "Mission Statement"
            name: missionStatement
            widget: object
            required: false
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Statement, name: content, widget: text}
          - {label: "Background Image", name: backgroundImage, widget: image}
          - label: "Social Media"
            name: socialMedia
            widget: list
            required: false
            fields:
              - {label: Icon, name: icon, widget: image}
              - {label: Link, name: link, widget: string}
          - label: Heading
            name: homePageHeading
            widget: object
            required: false
            fields:
              - {label: "Top Text", name: topText, widget: string, default: 'Top text'}
              - {label: "Bottom Text", name: bottomText, widget: string, default: 'Bottom Text'}
          - label: "Ensembles"
            name: ensembles
            widget: list
            fields:
              - {label: Image, name: image, widget: image, default: '/img/cu-singers.jpg'}
              - {label: Heading, name: heading, widget: text, default: 'Heading'}
              - {label: "Short Description", name: description, widget: text, default: 'Short Description'}
              - label: Button
                name: button
                widget: object
                fields:
                  - {label: "Button Label", name: buttonText, widget: string}
                  - {label: "Button Link", name: buttonLink, widget: string}
      - file: "src/pages/concerts/index.md"
        label: Concerts
        name: concerts
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "concerts-page"}
          - label: Heading
            name: concertsPageHeading
            widget: object
            fields:
              - {label: "Top Text", name: topText, widget: string, default: "Clemson Vocal Arts"}
              - {label: "Bottom Text", name: bottomText, widget: string, default: "Concerts"}
          - label: Concerts
            name: concerts
            widget: list
            fields:
              - {label: "Hook Photo", name: photo, widget: string}
              - {label: "Show title on the first part of the slider", name: showTitle, widget: boolean, default: true}
              - {label: "Title", name: title, widget: string, default: "Example Title"}
              - {label: "Date", name: date, widget: datetime, dateFormat: "MMM Do, YYYY", timeFormat: "hh:mm a"}
              - {label: "Long description", name: description, widget: text, default: "This is the long description"}
              - label: Button
                name: button
                widget: object
                fields:
                  - {label: "Button Label", name: buttonText, widget: string}
                  - {label: "Button Link", name: buttonLink, widget: string}
              - {label: Location, name: location, widget: 'map', default: '{"type":"Point","coordinates":[0,0]}'}
              - {label: "Show location on the last part of the slider", name: showLocation, widget: boolean, default: true}
              - label: "Second description (for the last part if no location)"
                name: secondDescription
                widget: object
                fields:
                  - {label: Subtitle, name: subtitle, widget: string, default: "Example Subtitle"}
                  - {label: Description, name: description, widget: text, default: "Example description"}
      - file: "src/pages/staff/index.md"
        label: "Staff Page"
        name: staff
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "staff-page"}
          - label: Heading
            name: staffHeading
            widget: object
            fields:
              - {label: "Top Text", name: topText, widget: string, default: 'Top text'}
              - {label: "Bottom Text", name: bottomText, widget: string, , default: 'Bottom Text'}
          - label: Staff
            name: staffList
            widget: list
            fields:
              - {label: Image, name: image, widget: image}
              - {label: Name, name: name, widget: text}
              - {label: Title, name: title, widget: text}
              - {label: Bio, name: bio, widget: text}
              - {label: Email, name: email, widget: text}
